spring.application.name=beam
spring.datasource.url=jdbc:mysql://localhost:3306/beam
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret="26ace47b7fb8b5ef4a806c60a5822d67af6b4bc35cd34031143f42e595364220"
